version: "2"
services:
  flask:
    container_name: avatar-gen-flask
    build: .
    command: gunicorn app:app -c gunicorn.conf
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - .:/compose
    networks:
      - flask-redis-celery

  redis:
    container_name: avatar-gen-redis
    image: 'redis'
    command: redis-server
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./compose:/data
    networks:
      - flask-redis-celery

  celery:
    container_name: avatar-gen-celery
    build: .
    command: celery -A app.celery worker --loglevel=info --autoscale=4,2
    restart: always
    volumes:
      - .:/compose
    networks:
      - flask-redis-celery

networks:
    flask-redis-celery:
